"""
Python 3.13
HLA Fusion PDF Report Splitter GUI Frontend

This script provides a simple graphical interface for splitting multi-report PDFs
generated by HLA Fusion into individual reports named by Sample ID. It wraps around the
'reportsplitter' backend logic and provides an easy-to-use workflow for
HLA Fusion users.

Main Features:
- Launches a Tkinter GUI to select a PDF file
- Displays the selected file name
- Calls the report splitting function on button click
- Automatically closes the interface after splitting

Intended Use:
This tool is designed for use in a laboratory setting to streamline the
process of separating PRA or SAB reports (Class I or II) from HLA Fusion output.

Dependencies:
- Python 3.8+
- tkinter (standard with Python)
- reportsplitter (custom module that performs the actual PDF processing)
"""


import tkinter as tk
from tkinter import filedialog
import reportsplitter
import os

class FileInfo:
    """
    A simple class to store and update the file path of the selected PDF.

    Attributes:
        filepath (str): The path to the selected PDF file.
    """
    def __init__(self, ifilepath):
        """
        Initializes a FileInfo instance with a default file path.

        Args:
            ifilepath (str): Initial file path.
        """
        self.filepath = ifilepath

    def filepathupdater(self, newfilepath):
        """
        Updates the stored file path.

        Args:
            newfilepath (str): The new file path to update to.
        """
        self.filepath = newfilepath

def askfor_openfile():
    """
    Opens a file dialog for the user to select a PDF file.
    Updates the file path in the FileInfo instance and displays the filename in the GUI.
    """
    choosefile = filedialog.askopenfilename(title="Select file to split")
    filetosplit.filepathupdater(choosefile)
    filename = os.path.basename(filetosplit.filepath)
    output_label.config(text=filename)

def split_file():
    """
    Calls the report splitter on the selected file and closes the application after processing.
    """
    reportsplitter.main(filetosplit.filepath)
    root.destroy()

# --- GUI Setup ---

root = tk.Tk()
root.title("HLA Fusion Report Splitter")
root.geometry("150x150+20+50")

# Create a FileInfo object with a placeholder path (will be updated after file selection)
filetosplit = FileInfo("unknown")

# Button to select the PDF file
filebutton = tk.Button(root, text="Select file", command=askfor_openfile)
filebutton.pack(padx=20, pady=12)

# Label to show selected file name
output_label = tk.Label(root, text="No file selected")
output_label.pack(pady=10)

# Button to split the PDF into individual reports
splitbutton = tk.Button(root, text="Split file", command=split_file)
splitbutton.pack(padx=20, pady=20)

# Start the GUI event loop
root.mainloop()
